---
title: "Class 2 - Data Exploration"
output:
  pdf_document: default
  html_document: default
editor_options: 
  markdown: 
    wrap: 72
---

## Load Libraries

```{r}
library(psych)
library(corrgram)
```

# Load Dataset

```{r setup, include=TRUE, echo=T}
knitr::opts_chunk$set(echo = TRUE)
marketing = read.csv("E:/MSc DSc/Sem 1/Business Analytics/Ch3_marketing.csv", stringsAsFactors = TRUE)
str(marketing)
```

```{r}
marketing$pop_density = factor(marketing$pop_density,
                                ordered = TRUE,
                                levels = c('Low','Medium','High'))
```

Focusing on google_adwords, and pop_density

```{r}
summary(marketing$pop_density)
```

```{r}
summary(marketing$google_adwords)
```

```{r}
sd(marketing$google_adwords)
```

```{r}
var(marketing$google_adwords)
```

## Tabular Exploration

```{r}
summary2 = function(x) {
    results = c(summary(x),'StdDev.' = sd(x),'Var.' = var(x), 'IQR' = IQR(x))
    return(results)
}
summary2(marketing$google_adwords)
```

```{r}
summary3 = function(x) {
    results = c('Min' = min(x), 
                'Q1' = quantile(x, 0.25), 
                'Median' = median(x), 
                'Mean' = mean(x), 
                'Q3' = quantile(x, 0.75), 
                'Max' = max(x), 
                'StdDev' = sd(x), 
                'Var' = var(x),
                'IQR' = IQR(x))
    results
}
summary3(marketing$google_adwords)
```

```{r}
summary(marketing$pop_density)
```

## Graphical Exploration

```{r}
#layout(matrix(1:4,ncol = 2)) # or par(mfrow = c(2,2))
par(mfrow=c(2,2))
boxplot(marketing$google_adwords, ylab = 'Expenditures', main = 'Google')
hist(marketing$google_adwords, main = 'Google', xlab = NULL)
boxplot(marketing$twitter, ylab = 'Expenditures', col = 'blue', main = 'Twitter')
hist(marketing$twitter, col = 'blue', main = 'Twitter', xlab = NULL)
par(mfrow=c(1,1))
```

## Analyzing two variables together

```{r}
summary(marketing)
marketing$emp_factor = cut(marketing$employees , 2)
```

```{r}
levels(marketing$emp_factor) = c('Low Employee', 'High Employee')
table1 = table(marketing$pop_density,marketing$emp_factor)
table1
```

```{r}
par(mfrow=c(1,3))
mosaicplot(table1, 
            col=c('gray','black'), 
            main = 'Factor / Factor')
boxplot(marketing$marketing_total ~ marketing$pop_density, 
        main = 'Factor / Numeric')
plot(marketing$revenues, marketing$google_adwords,
    main = 'Numeric / Numeric')
par(mfrow=c(1,1))
```

## Correlation

```{r}
cor(marketing$google_adwords,marketing$revenues)
#cor(marketing$google_adwords, marketing$facebook)
```

```{r}
cor.test(marketing$google_adwords, marketing$revenues)
```

```{r}
cor_test = function(x,y) {
    results = cor.test(x,y)
    output = c(#'Data' = results$data.name, 
                'Correlation Coefficient' = results$estimate, 
                'p-value' = results$p.value)
    output
}
```

```{r, echo=TRUE, include=FALSE}
a = cor_test(marketing$google_adwords, marketing$revenues)
str(a)
colnames(marketing)
for (item in colnames(marketing)) {
    for(item2 in colnames(marketing)) {
        if(is.numeric(marketing[[item]]) & is.numeric(marketing[[item2]])) {
            result = cor_test(marketing[[item]],marketing[[item2]])
            print(result)
        }
    }
}
```

```{r, echo=TRUE, include=FALSE}
for(item in colnames(marketing)) {
    for(item2 in colnames(marketing)) {
        print(marketing[[item]])
        print(item2)
    }
}
```

```{r}
cor(marketing[,1:6])
```

```{r}
corr.test(marketing[,1:6])
```

```{r}
pairs(marketing)
```

## Corrgram

```{r}
corrgram(marketing,order=TRUE,
         main = "Correlogram of Marketing Data Ordered",
         lower.panel = panel.shade,
         upper.panel = panel.ellipse,
         diag.panel = panel.minmax,
         text.panel = panel.txt)

```

```{r, warning=FALSE}
corrgram(marketing,order=FALSE,
         main = "Correlogram of Marketing Data Unordered",
         lower.panel = panel.conf,
         upper.panel = panel.shade,
         diag.panel = panel.minmax,
         text.panel = panel.txt)
```

\
