---
title: "Class 5 - Cluster Analysis"
output:
    pdf_document: default
knitr:
  opts_chunk: 
    echo: true
    include: true
    message: false  # Optional: Hide messages
    warning: false  # Optional: Hide warnings
---

# K-Means

```{r, include=F}
library(tidyverse)
```

```{r}
stations = read.csv("G:/My Drive/Master-Data-Science/Semester_1/Business_Analytics/Data/Ch5_bike_station_locations.csv")
```

```{r}
two = kmeans(stations, 2)
two
```

```{r}
three = kmeans(stations, 3)
three
```

```{r}
four = kmeans(stations, 4)
four
```

```{r}
clus = cbind(stations, clu2 = two$cluster, clu3 = three$cluster)
head(clus)
```

```{r}
plot(clus$longitude, clus$latitude, col = two$cluster, asp = 1, pch = two$cluster, main = 'Sites for two kiosk')
points(two$centers[,2], two$centers[,1], pch = 23, col = 'maroon', bg = 'lightblue', cex=3)
text(two$centers[,2], two$centers[,1], cex = 1.1, col = 'black', attributes(two$centers)$dimnames[[1]])
```

```{r}
plot(clus$longitude, clus$latitude, col = three$cluster, asp = 1, pch = three$cluster, main = 'Sites for three kiosk')
points(three$centers[,2], three$centers[,1], pch = 23, col = 'maroon', bg = 'lightblue', cex=3)
text(three$centers[,2], three$centers[,1], cex = 1.1, col = 'black', attributes(three$centers)$dimnames[[1]])
```

```{r}
d3 = rep(0,244)
for (i in 1:244) {
  if (three$cluster[i] == 1) {
    d3[i] = sqrt((clus$latitude[i] - three$centers[1,1])^2 + (clus$longitude[i] - three$centers[1,2])^2)
  }
  if (three$cluster[i] == 2) {
    d3[i] = sqrt((clus$latitude[i] - three$centers[2,1])^2 + (clus$longitude[i] - three$centers[2,2])^2)
  }
  else {
    d3[i] = sqrt((clus$latitude[i] - three$centers[3,1])^2 + (clus$longitude[i] - three$centers[3,2])^2)
  }
}

d2 = rep(0,244)
for (i in 1:244) {
  if (three$cluster[i] == 1) {
    d2[i] = sqrt((clus$latitude[i] - two$centers[1,1])^2 + (clus$longitude[i] - two$centers[1,2])^2)
  }
  else {
    d2[i] = sqrt((clus$latitude[i] - two$centers[2,1])^2 + (clus$longitude[i] - two$centers[2,2])^2)
  }
}

par(mfrow = c(1,2))
hist(d3)
hist(d2)
```

```{r}
test = data.frame(
  measure = c('mean distance', 'maximum distance'),
  '2-cluster' = c(mean(d2), max(d2)),
  '3-cluster' = c(mean(d3), max(d3))
)
test
```

## Scaling Data

```{r}
market = read.csv("G:/My Drive/Master-Data-Science/Semester_1/Business_Analytics/Data/Ch5_age_income_data.csv")
head(market)
```

```{r}
summary(market)
```

```{r}
test1 = kmeans(market[,c(2,3)], 3)

clust1 = cbind(market, clu2 = test1$cluster)

plot(clust1$age, clust1$income, col = test1$cluster, pch = test1$cluster, main= 'Three Cluster without Scale')
points(test1$centers[,1], test1$centers[,2], pch = 23, col = 'maroon', bg = 'lightblue', cex = 3)
text(test1$centers[,1], test1$centers[,2], cex = 1.1, col = 'black', attributes(test1$centers)$dimnames[[1]])
```

```{r}
market$age_scale = as.numeric(scale(market$age))
market$income_scale = as.numeric(scale(market$income))
head(market,10)
```

```{r}
test2 = kmeans(market[,c(4,5)], 3)

clust2 = cbind(market, clu2 = test2$cluster)

plot(clust2$age, clust2$income, col = test2$cluster, pch = test2$cluster, main= 'Three Cluster with Scale')
points(test2$centers[,1], test2$centers[,2], pch = 23, col = 'maroon', bg = 'lightblue', cex = 3)
text(test2$centers[,1], test2$centers[,2], cex = 1.1, col = 'black', attributes(test2$centers)$dimnames[[1]])
```

```{r}
test2$centers
```

Unscale data

```{r}
#unscale each of the scaled values in the scaled_data vector
#scaled_data * attr(scaled_data, 'scaled:scale') + attr(scaled_data, 'scaled:center')
```

# Hierarchical Techniques

```{r}
set.seed(456)
hc_mod = hclust(dist(market[,4:5]), method = 'ward.D2')
hc_mod
```

```{r}
library(dendextend)
```

```{r}
dend = as.dendrogram(hc_mod)
dend_six_color = color_branches(dend, k = 6)
plot(dend_six_color, leaflab = "none", horiz = F,
     main = 'Age and Income Dendogram', ylab = 'Height')
abline(h = 37.5, lty= 'dashed', col = 'blue')
```

```{r}
str(cut(dend, h =37.5)$upper)
```

# Evaluating models

```{r}
optimize = data.frame(
  clusters = c(2:10),
  wss = rep(0,9)
)

for (i in seq(2, 10, by=1)) {
  x = kmeans(market[,4:5], i)
  optimize[i-1,2] = as.numeric(x$tot.withinss)
}

plot(optimize$wss ~ optimize$clusters, type = 'b',
     main = 'Finding optimal number of clusters based on error',
     xlab = 'Number of Clusters',
     ylab = 'Within Sum of Squared Error')
```

```{r}
# Cluster 5
five = kmeans(market[,4:5], 5)

market$clus5 = five$cluster
dend_five = cutree(dend, k = 5)
market$dend5 = dend_five

# Cluster 6
six = kmeans(market[,4:5], 6)

market$clus6 = six$cluster
dend_six = cutree(dend, k = 6)
market$dend6 = dend_six
```

```{r fig.height=10, fig.width=10}
par(mfrow = c(2,2))
plot(market$age, market$income, col=five$cluster,
     pch = five$cluster, xlab='', main='5-means Clustering')
plot(market$age, market$income, col=six$cluster,
     pch = six$cluster, xlab='', main = '6-means Clustering')
plot(market$age, market$income, col=market$dend5,
     pch = market$dend5, ylab='', main='k=5  Hierarchical')
plot(market$age, market$income, col=market$dend6,
     pch=market$dend6, ylab='', main='k=6, Hierarchical')
```

Showing median with labels

```{r}
labels = as.data.frame(market %>%
                         group_by(dend6) %>%
                         summarise(
                           avg_age = median(age), 
                           avg_inc = median(income)
                           )
                       )
labels
```

```{r}
plot(market$age, market$income, col = market$dend6,
     pch = market$dend6, xlab='Age', ylab='Income',
     main ='Marketing Clusters from Hierarchical Clustering \n (Labels show median ogf age and income of cluster)')
points(labels[,2], labels[,3], pch = 21, col='maroon', bg='white', cex = 2)
text(labels[,2], labels[,3], col ='black', cex = 1, labels[,1])
```

```{r}
market %>% group_by(dend6) %>% summarise(Clustersize = n())
```

```{r}
market %>% group_by(dend6) %>%
  summarise(
    min_age = min(age),
    med_age = median(age),
    max_age = max(age),
    min_inc = min(income),
    med_inc = median(income),
    max_inc = max(income)
  )
```

```{r}

custom_labels = c(
  "Professionals",
  "Juniors",
  "Fresh Grads",
  "Pensioners",
  "Old Gov Servants",
  "High Achievers"
)

market %>% group_by(dend6) %>%
  summarise(
    Age_Range = paste(min(age),'-',max(age)),
    Age_Median = median(age),
    Income_range = paste(round(min(income),2),'-',round(max(income),2)),
    Income_Median = median(income)
  ) %>%
  mutate(Label = custom_labels)
```
